// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCuzEq0BpMH-pnlLMXvclFteM9uoUFcBLU',
//     appId: '1:32419985747:web:961955febb31a5deab09a6',
//     messagingSenderId: '32419985747',
//     projectId: 'dronear-ac509',
//     authDomain: 'dronear-ac509.firebaseapp.com',
//     storageBucket: 'dronear-ac509.firebasestorage.app',
//     measurementId: 'G-02XKEC4N73',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBBWwDvRtMrlwTfo_MYAD4X7TUMlDKgX9Q',
//     appId: '1:32419985747:android:c0eeb26295430da3ab09a6',
//     messagingSenderId: '32419985747',
//     projectId: 'dronear-ac509',
//     storageBucket: 'dronear-ac509.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAXqKox95ctgGsVGogg6-QgXN7TX6gfrZ4',
//     appId: '1:32419985747:ios:15a0f75e24668a5dab09a6',
//     messagingSenderId: '32419985747',
//     projectId: 'dronear-ac509',
//     storageBucket: 'dronear-ac509.firebasestorage.app',
//     iosBundleId: 'com.example.dronear',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAXqKox95ctgGsVGogg6-QgXN7TX6gfrZ4',
//     appId: '1:32419985747:ios:15a0f75e24668a5dab09a6',
//     messagingSenderId: '32419985747',
//     projectId: 'dronear-ac509',
//     storageBucket: 'dronear-ac509.firebasestorage.app',
//     iosBundleId: 'com.example.dronear',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCuzEq0BpMH-pnlLMXvclFteM9uoUFcBLU',
//     appId: '1:32419985747:web:ba677b363496a30dab09a6',
//     messagingSenderId: '32419985747',
//     projectId: 'dronear-ac509',
//     authDomain: 'dronear-ac509.firebaseapp.com',
//     storageBucket: 'dronear-ac509.firebasestorage.app',
//     measurementId: 'G-5FR0QBRYP6',
//   );
// }
